sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: hQe8KzrAnwGg0HKfW6rp18ayk8ZidYsDdJEXiRO/sx75UVb3hLiKdo7P/M5F1QglsaToN0Rz2gssyN5g5Ut8iX3B0foiXI4Gtt1pSnpQz943hE5pGjS5igY9vkuvqGnhsoPZqHMjmQkVXhs64MZbfHNJB1XkdGi70WJuYqePF5VtkCNaGmTJmVU7jr1ATzjIH/vuq7AXhagYtjCcYulqhhwXM7hgBBMs7DnKKXT4RquJlYncMn3R6/Y/p5rDpszLL/DUoO7GRCK7cx51reC+Fofz6jUr+NhIUS7UkmQDeyQGBNAFVfsqoGutvfdSAXjcFOJtWzgJKTSx1vRNGXhKiuJY1qYqnMGi/nRFKXpldRyVY7pb5kwqAiq5/wStrDBWT21WSiWsuAvybP0JW1uv407+1ZabwFPFWhrIPrArE0zuX1dOCpuwFn/GoSuzjeq0fhIO6d74Us2di1Sr2n7ifEaGTV1eLYJH9WDoT60oec8dajiiIhWqMWf3GF9/SdmE9kRocEbv3dvV+qIhvQJh7fBzfhr/20HgsZ64tb1ZCCnEmcXCskCQZFB/ScjdvT5Du76tyzV9y4PMSbWF3a8JtnDCXgkw7eKXcXVjiIpS8hpbeCxgD2UYZfzctrP84QDnsxSacff/hqKy1bZxEPdg3bdjnA0T81xRLXQNEiCZuTM=
  - secure: Lr1PBFJN20Vg0IIp9vl2VTFVTSZBkQbKFy9qFZpIWhFvqxFw7Ar0rRAGplbzWz/GgMGRPwvjuDh2BiYjOW3UylAazLSx3Nw418OvMC7qA2WGQFstxy87cawNxRKu0zIYOgChINIoBLo3Ng9bA2naPMIoArekUbmfL9Ddih6qA4Ve8w5yeBAIGmOlTivntS+/Dr8nVYmmoh3nbvL45HVvUsy7MkfwIP6aWhjB85+iBLns/ckoC1qKWpKj0KaEY7QJDPeHxqhYhPlBDxHTlWjM1Dj0MfyA13sN71UOB5cuk1pWYdX2DEBCqBMrzYfG88cWIyBluVO4D9jXeTp6o+IyaYz5xq5G3NpZMJy04mf1HJ7ujq+03eFVBBsBWAzQAQUA2/T4kZH/ay7Zpn9lAJq39VYr56Md244gUmWPIJvL6b33pEB5hG1u2QDuOSFA4AAadulb5DELPvlkM0klE3Xcp0a+O5uKa8tuxQ5zsNwwnXiS0YkKFgewH8tfcaODndzZUlnmgvc4SsH9a8rvIt/lLpnLu1+4LxX5uV/tnqeJbMlqd5XnAsXQP5PqA0CkaXP/Ih8UxzMFsNCnmRM4itr6Y9aJ90LW+K+0m8z6gH/v29xgZBx5+QnPE72fxm8Fnr5zcDJZxKOf9Xcr76b80Jqc+F/F2Df5u8BxDuylaQ677eo=
  - secure: K/CiArpcFn9rHY88sbqi0Vb8RDxEm7IdCeed+OZzTWbG+OGHXwyJerDQiddtTGUFxcpq7ob2vlnlXefTKTayv2X8R0fFeJVNXQ2cH5lG/NYqRzVMs1J/fCsPUfI267dv9TwMZy99aQ4uiTlU16ppKenF3mhAyiYc12pbAgy/91nITddZ0ilyuxw8i+0y5zikYBOFbo4/eVZaTSMUzFc+bMnmpCMIPNC+X8QzLsBVl7J0ColVOvLH2j8rgof+Uxi9oRehUX2YTx6avhW5id0MzFQ2feBMraKRcYHHc0I0zYvxJnStHFT5M3I/53JMxchcODU0+bjkiUjQSzpYHey9I/F6/r45j4I1p5MpfVWdvZohyxTDFkRuMc/kj6A0UPyh64ZXV/QOjZlAJxWkknmnwDDeOvAhmvMY/myBXSDxyQTodhCgxEvWSaKSO7X4CVa43hOvYSbwlhn2O6xJBqZJiv29il09YawaCRwKVwiyW6/aVcUrLSImu1urYLRXxdW6CvBxMoVRhUQSumAqbdl2/7zm431JbcHYELvW6HE2xN9puldEl274ZnZ48hh7VDMC+4OKjL5uiHb8A/MxNLv3DZ1z9TVACo9dskqLJb8bpbFfaYBaCBvf8G+leH1XhafEFcP6dcgH1nTEUDawysy/UF6CK6v+IjCxGj+7db00Z8k=
  - secure: Xab0HNMN9hr8WeOJ3GcbTbKl2UPzMwpypYmQjgqQwNoZmuPcO8JWT3JzvWbQS+edeM0jFxnH0RWpgwvRINkd/f5aazsAaKxzZIdXUL3vts7kgZUUpmflBmCtGMaolsYer5Rkya/r+0kV04ZjMsz0/PEo2UgJ5NndgyeEee+zt+x5v+omJcz8/3gfzLUxHgtmhMPnOCUZT1cjh3/8+xZqR+P1zlR4nfYLWKe/PDE1a05hNll7amOtgAMySBp9LoGEoZGBrqNF9DCKYKOOgGG4qOY0Ha9OJAdcFhgm04iFdBL9YhenwQAx/kvXzJSekEGjR7TBCNuESkHhEcVdygCsFjgaw/1nMTbGT0zZmYddnziFEWLUU5UrRcaXr4AfANdBsPY0mBo5tvJNYutk7hfgJ1BZJYHyqIRRxh1E8ndod50bcYXbTe6A5zaSEXKOMNLvNVmsHxSYxvn7xcGus5J+4peTgKdlMCoOF0BVEfRiXbQEeZc8cQ1MKH/NQyxLjmK1TqzNun/Owsz1kA3K5aJDq3TH320FHCru1XBnrSRUYDbdZ0Yyr87d5XKgXr8vo5tDsPUIeQgqxN/ZhyEvND4nqzA0TBeVVheoFQbuyU17QGYGSw8yfuugfxeD2orcGA+1GKXY4tztJnR129kdCdUO3rmY+fdY58e3XsxWW18Yv+s=
